// Auto-generated from research/damage-calculator-data.json (observed 2026-08-25).
// Sources: mortalshelldb.com (single_source multipliers/ladder/poise, internally
// cross-checked), game8.co + fextralife wiki (weapon roster agreed x3).
// The game publishes no absolute damage/stagger numbers - everything here is
// upgrade multipliers applied to each weapon's own hidden base stats.

export type TarforgeRow = {
  level: number;
  material: string;
  amount: number;
  coin: number;
  cumulativeCoin: number;
};

export type PoiseEntry = { name: string; tier: string | null; maxPoise: number };

export type WeaponEntry = {
  name: string;
  slug: string;
  collectible: boolean;
  description: string;
  tarstones: { name: string; fits: string }[];
};

export const DAMAGE_MULT = [1.0, 1.05, 1.1, 1.15, 1.2, 1.25, 1.3, 1.35, 1.4, 1.45, 1.5, 1.55, 1.6, 1.65, 1.7, 1.75, 1.8] as const;
export const SECONDARY_MULT = [1.0, 1.05, 1.1, 1.15, 1.2, 1.25, 1.3, 1.35, 1.4, 1.45, 1.5, 1.55, 1.6, 1.65, 1.7, 1.75, 1.8, 1.85, 1.9, 1.95, 2.0] as const;
export const ZERO_BASE_MULT = [0, 1.05, 1.1, 1.15, 1.2, 1.25, 1.3, 1.35, 1.4, 1.45, 1.5, 1.55, 1.6, 1.65, 1.7, 1.75, 1.8, 1.85, 1.9, 1.95, 2.0] as const;
export const DAMAGE_CAP_LEVEL = 16;
export const MAX_SLIDER_LEVEL = 20;
export const GUARD_METER_DEFAULT = 1.25;
export const GUARD_METER_MARTYR = 1.3;
export const TARFORGE_LADDER: TarforgeRow[] = [{"level": 1, "material": "Ventrium", "amount": 1, "coin": 100, "cumulativeCoin": 100}, {"level": 2, "material": "Ventrium", "amount": 3, "coin": 300, "cumulativeCoin": 400}, {"level": 3, "material": "Ventrium", "amount": 6, "coin": 500, "cumulativeCoin": 900}, {"level": 4, "material": "Ventrium", "amount": 9, "coin": 1000, "cumulativeCoin": 1900}, {"level": 5, "material": "Ventrium", "amount": 12, "coin": 1250, "cumulativeCoin": 3150}, {"level": 6, "material": "Laterite", "amount": 1, "coin": 2000, "cumulativeCoin": 5150}, {"level": 7, "material": "Laterite", "amount": 3, "coin": 2750, "cumulativeCoin": 7900}, {"level": 8, "material": "Laterite", "amount": 6, "coin": 3500, "cumulativeCoin": 11400}, {"level": 9, "material": "Laterite", "amount": 9, "coin": 4250, "cumulativeCoin": 15650}, {"level": 10, "material": "Laterite", "amount": 12, "coin": 5000, "cumulativeCoin": 20650}, {"level": 11, "material": "Dorsalite", "amount": 1, "coin": 5750, "cumulativeCoin": 26400}, {"level": 12, "material": "Dorsalite", "amount": 3, "coin": 6500, "cumulativeCoin": 32900}, {"level": 13, "material": "Dorsalite", "amount": 6, "coin": 7250, "cumulativeCoin": 40150}, {"level": 14, "material": "Dorsalite", "amount": 9, "coin": 8000, "cumulativeCoin": 48150}, {"level": 15, "material": "Dorsalite", "amount": 12, "coin": 8750, "cumulativeCoin": 56900}, {"level": 16, "material": "Thoracium", "amount": 1, "coin": 9500, "cumulativeCoin": 66400}, {"level": 17, "material": "Thoracium", "amount": 3, "coin": 10250, "cumulativeCoin": 76650}, {"level": 18, "material": "Thoracium", "amount": 6, "coin": 11000, "cumulativeCoin": 87650}, {"level": 19, "material": "Thoracium", "amount": 9, "coin": 11750, "cumulativeCoin": 99400}, {"level": 20, "material": "Thoracium", "amount": 12, "coin": 12500, "cumulativeCoin": 111900}, {"level": 21, "material": "Ossinite", "amount": 1, "coin": 13250, "cumulativeCoin": 125150}, {"level": 22, "material": "Ossinite", "amount": 3, "coin": 14000, "cumulativeCoin": 139150}, {"level": 23, "material": "Ossinite", "amount": 6, "coin": 14750, "cumulativeCoin": 153900}, {"level": 24, "material": "Ossinite", "amount": 9, "coin": 15500, "cumulativeCoin": 169400}, {"level": 25, "material": "Ossinite", "amount": 12, "coin": 16250, "cumulativeCoin": 185650}];
export const POISE_ENTRIES: PoiseEntry[] = [{"name": "Hexapod", "tier": "Boss", "maxPoise": 1200}, {"name": "The Lost Child", "tier": "Boss", "maxPoise": 800}, {"name": "Magdalena, the Lady of the Woods", "tier": "Boss", "maxPoise": 500}, {"name": "The Monolith", "tier": "Boss", "maxPoise": 500}, {"name": "Zmey, the Unbidden", "tier": "Boss", "maxPoise": 500}, {"name": "Droeg, the Conquerer", "tier": "Boss", "maxPoise": 400}, {"name": "Orrem, the Discarded Golem", "tier": "Boss", "maxPoise": 400}, {"name": "Orrem, the Reclaimed", "tier": "Boss", "maxPoise": 400}, {"name": "The Nameless Captive", "tier": "Boss", "maxPoise": 400}, {"name": "Malborn Offspring", "tier": "Boss", "maxPoise": 350}, {"name": "Caged Grisha", "tier": "Miniboss", "maxPoise": 300}, {"name": "Pale Grisha", "tier": "Miniboss", "maxPoise": 300}, {"name": "Sir Isaac, the Scholar-Prince", "tier": "Boss", "maxPoise": 300}, {"name": "Grisha", "tier": "Miniboss", "maxPoise": 270}, {"name": "Tarblighted Stoner", "tier": null, "maxPoise": 300}, {"name": "Grisha Attributes", "tier": null, "maxPoise": 250}, {"name": "Strange Grisha", "tier": "Miniboss", "maxPoise": 250}, {"name": "The Warden", "tier": "Miniboss", "maxPoise": 250}, {"name": "Vrago, Solikar Champion", "tier": null, "maxPoise": 250}, {"name": "Zmee, the Royal Guard", "tier": "Miniboss", "maxPoise": 250}, {"name": "Starved Harridan", "tier": null, "maxPoise": 240}, {"name": "Tishina's Confessor", "tier": "Miniboss", "maxPoise": 220}, {"name": "Ball Boy", "tier": null, "maxPoise": 200}, {"name": "Cannibal Knight", "tier": null, "maxPoise": 200}, {"name": "Cannibal Knight Zombie", "tier": null, "maxPoise": 200}, {"name": "Great Arbiter of Flesh", "tier": "Miniboss", "maxPoise": 200}, {"name": "Infested Miner", "tier": "Miniboss", "maxPoise": 200}, {"name": "Prophet of Profane Infinities", "tier": "Miniboss", "maxPoise": 200}, {"name": "Stray Sesters", "tier": "Miniboss", "maxPoise": 200}, {"name": "Tainted Vestige", "tier": "Miniboss", "maxPoise": 200}, {"name": "Tanky Brigand", "tier": null, "maxPoise": 200}, {"name": "Tanky Brigand Sword", "tier": null, "maxPoise": 200}, {"name": "The Silent Sester", "tier": "Miniboss", "maxPoise": 200}, {"name": "Twin Sisters", "tier": "Miniboss", "maxPoise": 200}, {"name": "Urrig, the Executioner", "tier": "Miniboss", "maxPoise": 190}, {"name": "Solnir, the Gloom Seeker", "tier": "Miniboss", "maxPoise": 180}, {"name": "Tarred Vestige", "tier": null, "maxPoise": 175}, {"name": "Aristocrat", "tier": null, "maxPoise": 160}, {"name": "Vellen, High Lord of Mammon", "tier": null, "maxPoise": 160}, {"name": "Bloodcursed Lithopod", "tier": "Miniboss", "maxPoise": 150}, {"name": "Brigand Ranged Tanky", "tier": null, "maxPoise": 150}, {"name": "Lucian, the Thirsting Knight", "tier": "Miniboss", "maxPoise": 150}, {"name": "Shellsnatcher", "tier": null, "maxPoise": 150}, {"name": "Subjugated Guardian", "tier": null, "maxPoise": 150}, {"name": "Tanky Brigand Bronze", "tier": null, "maxPoise": 150}];
export const WEAPONS: WeaponEntry[] = [{"name": "Axatana", "slug": "axatana", "collectible": true, "description": "Forged by an unrepentant smith, this exquisite weapon once bore the name \"Dream Thresher.\"", "tarstones": [{"name": "Shrike Stone", "fits": "Fits 2"}, {"name": "Hexapod Core", "fits": "This one only"}]}, {"name": "Axe & Dagger", "slug": "axe-dagger", "collectible": true, "description": "An unusual pairing of a simple thieve's tool and a vicious axe from the northern lands.", "tarstones": [{"name": "Magdalena's Memento", "fits": "This one only"}]}, {"name": "Black Needle", "slug": "black-needle", "collectible": true, "description": "Stolen from the Twiceborn, this spear enables the bearer to reach further and more quickly than seems physically plausible.", "tarstones": [{"name": "Conqueror's Reward", "fits": "This one only"}, {"name": "Infused Stone", "fits": "This one only"}]}, {"name": "Clockwork Scythe", "slug": "clockwork-scythe", "collectible": true, "description": "The ambitious instrument of a madman or a genius, perhaps he was in fact both.", "tarstones": [{"name": "Scholar's Wormstone", "fits": "This one only"}, {"name": "Clockwork Shardstone", "fits": "This one only"}]}, {"name": "Great Martyr's Blade", "slug": "great-martyr-s-blade", "collectible": true, "description": "The devout weapon of the First Martyr Tarsus, reforged after his final sacrifice.", "tarstones": [{"name": "Captive's Scabstone", "fits": "This one only"}]}, {"name": "Obsidian Hammer", "slug": "obsidian-hammer", "collectible": true, "description": "A brutalist chunk of obsidianite, profaned by bloodshed beyond the Seat of Infinity.", "tarstones": [{"name": "Colossus Stone", "fits": "This one only"}, {"name": "Lost Clotstone", "fits": "Fits 2"}]}, {"name": "The Iconoclast", "slug": "the-iconoclast", "collectible": true, "description": "Exceptionally light for a two-hander, it was once held by a seedbearer of great renown", "tarstones": [{"name": "Shrike Stone", "fits": "Fits 2"}]}, {"name": "Veteran's Battle Axe", "slug": "veteran-s-battle-axe", "collectible": true, "description": "This solid steel axe is rumored to have been quenched in the blood of the Revered.", "tarstones": [{"name": "Lost Clotstone", "fits": "Fits 2"}]}, {"name": "Fists", "slug": "fists", "collectible": false, "description": "", "tarstones": []}, {"name": "Hallowed Sword", "slug": "hallowed-sword", "collectible": false, "description": "", "tarstones": []}];
